name: Build Executables

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --name="Game" --add-data "Assets;Assets" main.py

    - name: Upload Windows executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Build
        path: dist/Game.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Linux executable
      run: |
        pyinstaller --onefile --name="Game" --add-data "Assets:Assets" main.py

    - name: Upload Linux executable artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Build
        path: dist/Game
